spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
  jackson:
    date-format: "dd/MM/yyyy hh:mm:ss.SSS"


